### ISSUE TITLE
An error occurred during the fetch of repository 'com_github_nelhage_rules_boost'

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark#532]
I have no idea what's wrong with 'com_github_nelhage_rules_boost', the error keeps occuring with even vpn on.
```bash
(venv)...:~/bark$ bazel test //...
Starting local Bazel server and connecting to it...
INFO: Repository com_github_nelhage_rules_boost instantiated at:
  /home/tinmode/bark/WORKSPACE:9:18: in <toplevel>
  /home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bark_project/tools/deps.bzl:34:11: in bark_dependencies
  /home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bark_project/tools/deps.bzl:120:18: in _maybe
Repository rule git_repository defined at:
  /home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'com_github_nelhage_rules_boost':
   Traceback (most recent call last):
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
		update = _clone_or_update(ctx)
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
		git_ = git_repo(ctx, directory)
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
		init(ctx, git_repo)
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
		_error(ctx.name, cl, st.stderr)
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init /home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/com_github_nelhage_rules_boost' while working with @com_github_nelhage_rules_boost:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
		update = _clone_or_update(ctx)
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
		git_ = git_repo(ctx, directory)
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
		init(ctx, git_repo)
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
		_error(ctx.name, cl, st.stderr)
	File "/home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init /home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/com_github_nelhage_rules_boost' while working with @com_github_nelhage_rules_boost:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
ERROR: no such package '@com_github_nelhage_rules_boost//boost': error running 'git init /home/tinmode/.cache/bazel/_bazel_tinmode/eed35bca151b9786939218b1ff3c4a84/external/com_github_nelhage_rules_boost' while working with @com_github_nelhage_rules_boost:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
INFO: Elapsed time: 2.404s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```
the issue is similar to #491 , could you please give me some advices?

**Comment by tinmodeHuang** [comment]
the problem occurs in the branch 'bark_parametric_observer', I think about it again and get the workaround that the latest release is used
